### ISSUE TITLE
Wrong dependency in setup.cfg?

### ISSUE THREAD

**Issue by ali1234** [M-o-a-T/anyio_serial#1]
https://github.com/M-o-a-T/anyio_serial/blob/main/setup.cfg#L28

The `serial` project doesn't appear to have anything to do with serial ports. Did you mean to depend on `pyserial` instead?

https://pypi.org/project/serial/ vs https://pypi.org/project/pyserial/

**Comment by smurfix** [comment]
You're right. Thanks for noticing. Will update shortly.
