### ISSUE TITLE
0.3.1 tag does not match v0.3.1 PyPI distributions

### ISSUE THREAD

**Issue by gschaffner** [M-o-a-T/anyio_serial#9]
The 0.3.1 tag currently points to eee2e4df3b50f10d71d2e76b6f4fe7920a301efd, while the code in the v0.3.1 PyPI distributions matches 048b709e088e7048e04616274507da79f1301b1c (`main`, currently). Was the wrong commit tagged?

**Comment by smurfix** [comment]
Yeah, I have too many computers with source code on them. Sorry about that.
I'll release a 0.3.2 to clean that up.

**Comment by smurfix** [comment]
Done.
